apiVersion: v1
kind: Service
metadata:
  name: sftp
  labels:
    {{- include "test_chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sftp.type }}
  ports:
    - port: {{ .Values.sftp.port }}
      targetPort: 22
      name: ssh
  selector:
    app.kubernetes.io/component: sftp
