apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test_chart.fullname" . }}
  labels:
    {{- include "test_chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.sftp.replicaCount }}
  {{- end }}
  minReadySeconds: 10
  selector:
    matchLabels:
      {{- include "test_chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        container.apparmor.security.beta.kubernetes.io/sftp: runtime/default
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: sftp
        {{- include "test_chart.selectorLabels" . | nindent 8 }}

    spec:
      #secrets and config
      volumes:
      - name: sftp-public-keys
        configMap:
          name: sftp-public-keys

      containers:
        #the sftp server itself
        - name: sftp
          image: atmoz/sftp:latest
          imagePullPolicy: Always
          env:
#            - name: PASSWORD
#                valueFrom:
#                  secretKeyRef:
#                    name: sftp-server-sec
#                    key: password
          args: ["myUser::1001:100:incoming,outgoing"] #create users and dirs
          ports:
            - containerPort: 22
          volumeMounts:
            - mountPath: /home/myUser/.ssh/keys
              name: sftp-public-keys
              readOnly: true
          securityContext:
            capabilities:
              add: ["SYS_ADMIN"]
          resources: {}
